"""Added Indexes

Revision ID: 504b8ae4e935
Revises: 5c78c609964e
Create Date: 2026-09-29 13:38:33.588349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504b8ae4e935'
down_revision: Union[str, Sequence[str], None] = '5c78c609964e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_database_id'), 'conversations', ['database_id'], unique=False)
    op.create_index(op.f('ix_turns_conversation_id'), 'turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_user_databases_user_clerk_id'), 'user_databases', ['user_clerk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_databases_user_clerk_id'), table_name='user_databases')
    op.drop_index(op.f('ix_turns_conversation_id'), table_name='turns')
    op.drop_index(op.f('ix_conversations_database_id'), table_name='conversations')
    # ### end Alembic commands ###
