"""added database_soft

Revision ID: 79f3e0a3971e
Revises: f31eb58136ef
Create Date: 2026-09-11 14:40:02.378711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '79f3e0a3971e'
down_revision: Union[str, Sequence[str], None] = 'f31eb58136ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_databases', sa.Column('database_soft', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_databases', 'database_soft')
    # ### end Alembic commands ###
