""".

Revision ID: a2bf69685523
Revises: cae5ecf51864
Create Date: 2026-09-02 21:00:51.492122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bf69685523'
down_revision: Union[str, Sequence[str], None] = 'cae5ecf51864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_thread_id_key'), 'conversations', type_='unique')
    op.drop_column('conversations', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('conversations_thread_id_key'), 'conversations', ['thread_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
