"""added dense_schema

Revision ID: f31eb58136ef
Revises: db0d178d1efb
Create Date: 2026-09-02 23:00:06.230564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f31eb58136ef'
down_revision: Union[str, Sequence[str], None] = 'db0d178d1efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_databases', sa.Column('dense_schema', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_databases', 'dense_schema')
    # ### end Alembic commands ###
