"""made_database_name unique

Revision ID: 273b972c5c6e
Revises: 486e797cafb6
Create Date: 2026-08-18 20:19:56.720770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273b972c5c6e'
down_revision: Union[str, Sequence[str], None] = '486e797cafb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_databases', ['database_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_databases', type_='unique')
    # ### end Alembic commands ###
