"""created Conversations and Turns table

Revision ID: 3f3c52239d6b
Revises: 273b972c5c6e
Create Date: 2026-08-20 17:14:26.379858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f3c52239d6b'
down_revision: Union[str, Sequence[str], None] = '273b972c5c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('database_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['user_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turns')
    op.drop_table('conversations')
    # ### end Alembic commands ###
